### ISSUE TITLE
Update "How malware protection works" article

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#1007]
A very small update in this part:
https://kb.adguard.com/en/general/how-malware-protection-works#how-does-a-check-work

Now it's not just AdGuard for Windows that's using this approach, but also AdGuard for Mac and Android. The article needs to be updated accordingly.

**Comment by nataMai** [comment]
Added to jira/AG-11896

**Comment by nataMai** [comment]
Fixed in #1011
