### ISSUE TITLE
Specify the $replace modifier description for global usage

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/AdguardKnowledgeBase#1013]
@Baltazar500 commented on [Tue Jan 04 2022](https://github.com/AdguardTeam/AdguardFilters/issues/105549)

### Problem description

Сабж.

Как глобально применить фильтр $replace для всех сайтов ? Различные попытки манипуляций с данным фильтром ни к чему не привели. Он срабатывает лишь как довесок к определённому домену.

---

@Alex-302 commented on [Tue Jan 04 2022](https://github.com/AdguardTeam/AdguardFilters/issues/105549#issuecomment-1004771363)

Просто не указывайте адрес. По аналогии с этим:
`$replace=/aaaaaaa/bbbbbbb/`
Главное, чтобы регулярные выражения были корректными. Можно отлаживать на https://regex101.com/

---

@Baltazar500 commented on [Tue Jan 04 2022](https://github.com/AdguardTeam/AdguardFilters/issues/105549#issuecomment-1005024898)

>Просто не указывайте адрес. По аналогии с этим:
>$replace=/aaaaaaa/bbbbbbb/

А я по вашему так не пробовал  ? Я же выше писал "Различные попытки манипуляций с данным фильтром ни к чему не привели. Он срабатывает лишь как довесок к определённому домену." Предложенный вами вариант я в самом начале и применил. Но словил обломинго. Потом попробовал разные комбинации, но не прокатило. Работает только с доменом. Простая замена без всяких регекспов. 

>closed

Открывайте назад

---

@Alex-302 commented on [Tue Jan 04 2022](https://github.com/AdguardTeam/AdguardFilters/issues/105549#issuecomment-1005049139)

Неизвестно, что вы пробовали. Опишите по шагам.

---

@Baltazar500 commented on [Tue Jan 04 2022](https://github.com/AdguardTeam/AdguardFilters/issues/105549#issuecomment-1005057784)

>Неизвестно, что вы пробовали. Опишите по шагам.

Фильтр 

>```www.google.com$replace=/www.reddit.com/old.reddit.com/```

успешно работает в гугле. Фильтр

>```$replace=/www.reddit.com/old.reddit.com/```

в гугле, равно как и где-то ещё не работает.

---

@Alex-302 commented on [Tue Jan 04 2022](https://github.com/AdguardTeam/AdguardFilters/issues/105549#issuecomment-1005081800)

Покажите пример заменяемого текста, как он выглядит в страницах.

---

@Alex-302 commented on [Tue Jan 04 2022](https://github.com/AdguardTeam/AdguardFilters/issues/105549#issuecomment-1005083819)

Попробуйте так
`http$replace=/www.reddit.com/111.reddit.com/`

---

@Baltazar500 commented on [Tue Jan 04 2022](https://github.com/AdguardTeam/AdguardFilters/issues/105549#issuecomment-1005164237)

>```http$replace=/old.reddit.com/111.reddit.com/```

Этот фильтр сработал. А почему первый не срабатывает ? Ведь он по логике корректный.

---

@Baltazar500 commented on [Wed Jan 05 2022](https://github.com/AdguardTeam/AdguardFilters/issues/105549#issuecomment-1005451252)

Спасибо за помощь.

---

@Alex-302 commented on [Wed Jan 05 2022](https://github.com/AdguardTeam/AdguardFilters/issues/105549#issuecomment-1006035830)

> Этот фильтр сработал. А почему первый не срабатывает ? Ведь он по логике корректный.

Без пути(хоть какого-то уточнения, т.к. правило может много чего сломать) - некорректный. Защита от "дурака")

---

@Baltazar500 commented on [Thu Jan 06 2022](https://github.com/AdguardTeam/AdguardFilters/issues/105549#issuecomment-1006335581)

>Без пути(хоть какого-то уточнения, т.к. правило может много чего сломать) - некорректный. Защита от "дурака")

0_o

Но вы же в самом начале предложили именно этот вариант

>```$replace=/aaaaaaa/bbbbbbb/```

на грабли которого я и сам изначально встал (из-за чего и завёл issue). Или я что-то неправильно понял ? В любом случае, этот момент стоит отобразить в документации. По крайней мере поиском ни одного ```"http$"``` примера я не обнаружил (равно как и его описания).

---

@Alex-302 commented on [Sat Jan 08 2022](https://github.com/AdguardTeam/AdguardFilters/issues/105549#issuecomment-1007774766)

Да, надо описать. Просто без адреса давно не использовал этот тип правил.

**Comment by nataMai** [comment]
Moved to jira/AG-12185

**Comment by rosatea** [comment]
![Screenshot_20220325-005840_WireGuard.jpg](https://user-images.githubusercontent.com/94499426/160224403-9051c827-089a-4a34-8be5-41ca4dcc107f.jpg)

**Comment by sxgunchenko** [comment]
На стороне CoreLibs `$replace` правила, которые матчат слишком широкое множество ссылок (например, правила без маски (то, что до `$`) или маска матчит любую ссылку с заданным протоколом (`|http://$replace=/a/b/`)) считаются некорректными и откидываются (не принимают участия в фильтрации).

Это ограничение можно обойти, например, такой регуляркой в маске `/.*/` (`/.*/$replace=/a/b/`).
