### ISSUE TITLE
Screenshots need to be updated in the AdGuard KB to reflect UI changes

### ISSUE THREAD

**Issue by gGkAC3qfszbdViFkw4Fk9ooS2u** [AdguardTeam/AdguardKnowledgeBase#1034]
Many screenshots within the AdGuard KB for certain devices needs updating, such as the macOS AdGuard screenshots.
Many of them don't reflect the addition of DNS protection.

**Comment by NataKiss** [comment]
@gGkAC3qfszbdViFkw4Fk9ooS2u Thank you for your comment. We`re working on updating the Knowledge Base right now. So there will be changes with screenshots too.
