### ISSUE TITLE
Rules Syntax link from RU locale redirects to EN KB article

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardKnowledgeBase#105]
In UF on iOS apps (free and PRO versions) we have Rules Syntax link redirecting to knowledge base article [How to create your own ad filters](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters)

When system language is Russian, the article should be opened also in Russian.

**Comment by vbagirov** [comment]
This is a more broad problem. We just don't detect language at all when the user visits the KB. We should check the browser language first and then redirect to the appropriate page.

**Comment by vbagirov** [comment]
Now KB detects the browser language.
