### ISSUE TITLE
Add information about `Protect from DPI` (miscellaneous feature from Stealth Mode)

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardKnowledgeBase#1055]
- https://github.com/AdguardTeam/AdguardKnowledgeBase/blob/master/01.general/18.stealth-mode/docs.en.md#miscellaneous
- https://github.com/AdguardTeam/AdguardKnowledgeBase/blob/master/01.general/18.stealth-mode/docs.ru.md#miscellaneous

**Comment by slavaleleka** [comment]
`Remove X-Client-Data header` should also be described in the article

**Comment by rakleed** [comment]
Fixed in https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/1073
