### ISSUE TITLE
`:has` pseudo class is now supported by most browsers

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardKnowledgeBase#1129]
Update that the `:has` pseudo-class is now supported by most browsers. More: https://caniuse.com/css-has

https://github.com/AdguardTeam/AdguardKnowledgeBase/blob/master/01.general/02.how-to-create-your-own-ad-filters/docs.en.md#extended-css-has

**Comment by vbagirov** [comment]
We're still waiting for it to be internally implemented, it will likely be a part of this task:
https://github.com/AdguardTeam/ExtendedCss/issues/110
