### ISSUE TITLE
Add more information on how to setup AG + Tasker/AutomateIt

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#114]
Some useful posts:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=66145294
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=66145812

Also, we should add some screenshots to the article as it's hard to understand at the moment.

**Comment by vbagirov** [comment]
I believe it is done already.
https://kb.adguard.com/android/solving-problems/tasker
