### ISSUE TITLE
Add article about HTTPS filtering in the apps on Android 6+

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardKnowledgeBase#115]

**Comment by ameshkov** [comment]
Shouldn't we update the original HTTPS filtering article instead of adding a new one?

**Comment by vbagirov** [comment]
>Shouldn't we update the original HTTPS filtering article instead of adding a new one?
Yes, and we will.

**Comment by vbagirov** [comment]
@ameshkov @Alex-302 https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/117

**Comment by vbagirov** [comment]
https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/118 too

**Comment by vbagirov** [comment]
https://kb.adguard.com/general/https-filtering/https-filtering-known-issues
