### ISSUE TITLE
Why some scripts are removed in adguard filters????

### ISSUE THREAD

**Issue by saravanakumar1** [AdguardTeam/AdguardKnowledgeBase#120]
Some ThirdParty Scripts are removed in adguard filter  (Eg: in url: https://filters.adtidy.org/extension/chromium/filters/3.txt, you hve removed scripts like inplaybricks.com
linkexchange.com), Can i know the reason for script removable?

**Comment by vozersky** [comment]
Issue moved to [AdguardTeam/AdguardFilters #7849](https://github.com/AdguardTeam/AdguardFilters/issues/7849) via [**ZenHub**](https://www.zenhub.com/)

**Comment by vozersky** [comment]
@saravanakumar1 moved to https://github.com/AdguardTeam/AdguardFilters/issues/7849
