### ISSUE TITLE
Article about Android requests log

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#13]
Just like this one:
https://github.com/AdguardTeam/AdguardFilters/wiki/Android

1. How can user record requests log?
2. What's inside of that log?
3. How to get this log file for analysis (getting it from the device, using logcat for real-time analysis)

We also need to tell more about HAR files recording feature and how to analyze them.

**Comment by evgeniy-ADG** [comment]
Please add a description of 'record all', 'record http requests' and others types of the log.

**Comment by TPS** [comment]
Pt# 3 seems to be https://kb.adguard.com/en/android/solving-problems/logcat (https://github.com/AdguardTeam/AdguardKnowledgeBase/blob/master/pages/05.android/06.solving-problems/11.logcat/docs.en.md).  However, [Catlog](https://play.google.com/store/apps/details?id=com.nolanlawson.logcat) from `Alternative way for ROOT users` seems to no longer exist. D'y'all have a viable alternative? Would [Logs](https://play.google.com/store/apps/details?id=com.tananaev.logcat) do? _(I've not used it much.)_

**Comment by Dariamag** [comment]
https://kb.adguard.com/en/android/solving-problems/log
https://kb.adguard.com/en/android/solving-problems/logcat
https://kb.adguard.com/en/android/solving-problems/har
