### ISSUE TITLE
Исправить название на AdGuard

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardKnowledgeBase#131]
Написано Adguard, вместо AdGuard
Кстати, хотел спросить, почему официально принято AdGuard? Мне кажется, что Adguard больше подходит

**Comment by ministr91** [comment]
![screenshot_2017-12-02-02-19-00](https://user-images.githubusercontent.com/22351242/33507736-1d4a27b6-d6ff-11e7-8771-444a8087648e.png)
![screenshot_2017-12-02-02-19-05](https://user-images.githubusercontent.com/22351242/33507741-221c963e-d6ff-11e7-9b8b-db83e970b7f2.png)

**Comment by ministr91** [comment]
@ameshkov почему официально принято AdGuard? Мне кажется, что Adguard больше подходит

**Comment by ministr91** [comment]
Раньше можно было и так и такн

**Comment by ameshkov** [comment]
Да ну и сейчас можно и так и так, но в интерфейсе и текстах мы стараемся AdGuard использовать.

**Comment by vbagirov** [comment]
Ага просто пока не успели везде в базе знаний обновить написание. Со временем обязательно приведем всё к единому виду.

**Comment by ministr91** [comment]
@ameshkov что делает @vozersky ? Закрыл и открыл тему, добавил и удалил точно такой же знак.

**Comment by vbagirov** [comment]
@ministr91 перестаньте меншоны кидать направо и налево, это некрасиво и долго так продолжаться не может. Если хотите задать вопрос человеку, достаточно обратиться к нему напрямую.

**Comment by ministr91** [comment]
@vbagirov , меншоны не работают. Кидаешь или нет - итог один и тот же, не отвечает он

**Comment by vbagirov** [comment]
@ministr91 Меншоны работают прекрасно, потому я например каждый раз их вижу, когда вы меня не по делу отмечаете. Если ответа нет, может быть, человек занят, а может быть, вопрос некорректный или несущественный.

Конкретно в данном случае @vozersky массово выставлял метки задачам, и такой эффект возникает при попытке присвоить задаче уже существующую метку. 

В любом случае, проблема совершенно несуществующая, лучше используйте меншоны только в важных случаях, когда внимание того или иного человека действительно необходимо, а не просто для удовлетворения любопытства. Все темы прочитываются в любом случае, с меншонами или без.

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/AdguardKnowledgeBase/commit/03399b13a27fb5f17f2d6e3c08a466211341c3bc
