### ISSUE TITLE
Disabling "warn for unknown roots" in Opera

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#14]
https://forum.adguard.com/index.php?threads/%D0%92%D0%BE%D0%BF%D1%80%D0%BE%D1%81.6/page-31#post-120436

`browser://flags/#warn-for-unknown-root`

**Comment by Dariamag** [comment]
Please navigate me, is this still relevant?

**Comment by ameshkov** [comment]
Nope
