### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardKnowledgeBase#148]
https://kb.adguard.com/ru/android/solving-problems/adguard-outbound-proxy

![image](https://user-images.githubusercontent.com/15856304/34933422-66b9ccdc-f9df-11e7-9dcd-73d9f16ac488.png)

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/AdguardKnowledgeBase/commit/3470bfe09c7d32f634ad73e57495478786448dc8
