### ISSUE TITLE
Update the Android FAQ section

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardKnowledgebase#151]
The "[Why Wi-Fi and USB tethering do not work with AdGuard?](https://kb.adguard.com/en/android/faq#why-wi-fi-and-usb-tethering-do-not-work-with-adguard)" part, for instance, as it pauses protection and thus is compatible with tethering, no further actions required.

![image](https://user-images.githubusercontent.com/15856304/34999831-752ddcb0-faeb-11e7-993e-c274343d9f4c.png)

**Comment by nataMai** [comment]
Moved to jira/AG-10925
