### ISSUE TITLE
Ambiguity in Certificate Install

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#154]
@The-Commissioner commented on [Mon Feb 05 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2105)

FF 58.0.1
AG 6.2.437.2171
W10 x64

In [this](https://kb.adguard.com/en/windows/solving-problems/connection-not-trusted) article, it asks us to tick all the checkboxes while configuring trust settings.
While using the reinstall certificate, only the first of the checkboxes is checked and not the other two.

---

@vbagirov commented on [Thu Feb 08 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2105#issuecomment-364050729)

@The-Commissioner there is an important nuance here. The certificate is installed into browser, not into system, so the "software" here in FF's interpretation is various java and javascript applets. This checkbox does not affect Windows apps in any way.

I am not ready to tell you how FF interprets "email".

-----

RE: "While using the reinstall certificate, only the first of the checkboxes is checked and not the other two"
Is it 100% like this? We probably need to test this.

---

@The-Commissioner commented on [Fri Feb 09 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2105#issuecomment-364305982)

> @The-Commissioner there is an important nuance here. The certificate is installed into browser, not into system, so the "software" here in FF's interpretation is various java and javascript applets. This checkbox does not affect Windows apps in any way.

I am not ready to tell you how FF interprets "email".

Hello @vbagirov This was not my concern at all. My concern was for installing certificate you give one instructions at one place and do another set of instructions while doing it yourself.

---

@vbagirov commented on [Mon Feb 12 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2105#issuecomment-364918851)

@The-Commissioner this is what the 2nd part of my reply was about.

**Comment by ameshkov** [comment]
@vbagirov point 5 needs to be changed:
https://uploads.adguard.com/up04_7hfzg_The_connection_is_not_trusted_error__Adguard_Knowledgebase_.png

**Comment by vbagirov** [comment]
Merged to master. Soon will be deployed to release.
