### ISSUE TITLE
Add more information to the userscripts page

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgebase#16]
We should re-write the whole page.

Simple plan:

1. What is a userscript?
2. List of the recommended userscripts.
3. Where can I find more userscripts?
4. How can I develop my own userscripts?

**Comment by Bluscream** [comment]
Step 4 is important, especially to know what is compatible (Example: https://github.com/StylishThemes/GitHub-Dark-Script/issues/69)

**Comment by Dariamag** [comment]
Is the plan above still relevant?
https://kb.adguard.com/en/general/userscripts

**Comment by nataMai** [comment]
Moved to jira/AG-10907
