### ISSUE TITLE
Update the article about cleaning computer from Adware/Malware

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#17]
This is an old article:
https://kb.adguard.com/index.php?/Knowledgebase/Article/View/28/0/what-to-do-if-you-suspect-infection

We should use information from this forum thread:
https://forum.adguard.com/index.php?threads/how-to-remove-adware-and-malware-self-help.17578/

**Comment by Dariamag** [comment]
https://kb.adguard.com/en/technical-support/adware
