### ISSUE TITLE
An article on Android automation

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#175]
This article is necessary for this task:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1896

Plan of the article:

1. What kind of automation do we mean?
2. What are the popular automation apps?
3. How to setup AdGuard so that you could automate it?

Automation profile examples:

* Run AdGuard when a certain app starts up (and stop it once the app is not available anymore)

Also, you need to update the old "Tasker" article: https://kb.adguard.com/en/android/solving-problems/tasker

* The old API does not work in AdGuard v2.12
* Give a link to the new article

**Comment by vbagirov** [comment]
@ameshkov https://kb.adguard.com/en/android/solving-problems/tasker
