### ISSUE TITLE
Add $network modifier description to the article

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#18]
Important thing to note:

> @ameshkov if you use rules, contains ipv6, you should use "collapsed" syntax, e.g. use rule 
> [2001:4860:4860::8888]$network instead of [2001:4860:4860:0:0:0:0:8888]$network

**Comment by adbuker** [comment]
also, we support such kind or rules as '||example.org^$network' and can use it with `$app` modifier together as it described in https://github.com/AdguardTeam/AdguardForWindows/issues/1534

**Comment by zebrum** [comment]
For supporting UDP blocking in Mac version we need follow next rule.

Url part of the rule with network option must contain fully specified IP address
and may contain port. IPv6 address must be put in square brackets. Valid examples:

127.0.0.1$network
127.0.0.1:443$network
[ff08::8080]$network
[ff08::8080]:443$network

**Comment by TPS** [comment]
Can someone link directly to the article/section on `$network`?  I've tried to search for it myself, but am getting nowhere.
