### ISSUE TITLE
Add "Documentation for Administrators" to the knowledge base under AG for Windows section

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#180]
The English content:
https://gist.github.com/ameshkov/3d5009602ffd4eca70f98cd6d7b53e09

Here's what needs to be done:

1. Translate
2. Publish the release version of MSI to CDN
3. Make sure that it works as expected (ask for @adbuker help)
4. Push the pull request with the documentation here.

**Comment by vbagirov** [comment]
@ameshkov https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/181
