### ISSUE TITLE
Add more information about filters optimization

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#20]
https://forum.adguard.com/index.php?threads/does-adguard-for-ios-support-extended-css-selectors.19204/#post-125470

**Comment by ameshkov** [comment]
We should also describe which filters are optimization, what "hit" percent do we use and so forth.

**Comment by Dariamag** [comment]
https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/643
