### ISSUE TITLE
Update links to ad filters

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardKnowledgeBase#219]
These articles: 

https://kb.adguard.com/en/general/adguard-ad-filters
https://kb.adguard.com/ru/general/adguard-ad-filters

Current "View all the rules" links (e.g. https://filters.adtidy.org/extension/chromium/filters/11.txt) should be substituted with GitHub ones (e.g. https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/filter_11_Mobile/filter.txt). Same for all other filters.

**Comment by Dariamag** [comment]
https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/640
https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/641
