### ISSUE TITLE
Add "Useful ads" page

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#22]
Talking about this page:
https://adguard.com/en/whitelist.html

1. You should also change the page content. Please find the article plan below.
2. Add a redirect from the website to the knowledge base.

### Useful ads

**Disclaimer** it has nothing to do with the acceptable ads program, we don't take money for it.

We unblock only websites' self-promotion and search ads.
This is voluntary, you can choose either to block or not block this kind of ads.

#### What is search ads and why we consider it useful?

Contextual advertising in search engines helps you to find what you are looking for. The credibility of these ads is often higher than that of organic search results. This is because all the contextual ads have been manually moderated.

TODO: Add more arguments

#### What is websites self-promotion?

TODO: Describe what it is. For instance, promotion of the websites' own products. Link Adguard's filters policy, it is stated there that websites self-promotion should not be blocked on purpose.

#### What ads are on the list?

Search engines: Google, Yahoo, Bing, Ask, Yandex, DuckDuckGo.
TODO: We should also add startpage.com to the list.

#### Summary

**Comment by vozersky** [comment]
https://kb.adguard.com/en/general/search-ads-and-self-promotion

**Comment by ameshkov** [comment]
No redirect yet:
https://adguard.com/en/whitelist.html

**Comment by vozersky** [comment]
@mmigi @vbagirov  

please add redirect https://adguard.com/en/whitelist.html  -> https://kb.adguard.com/en/general/search-ads-and-self-promotion  and the same for RU

**Comment by vbagirov** [comment]
Redirect has been set up.
