### ISSUE TITLE
Add more information to the Filters Policy

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#23]
https://kb.adguard.com/en/general/adguard-filter-policy

It does not cover language-specific filters.
It does not cover "Filter for useful ads".
It does not cover "Annoyances filter".

Change "Anti-adblock scripts will be blocked only if they limit functionality of the website or interfere in its use." to "Anti-adblock scripts will be blocked if they provide no alternative to disabling an ad blocker".

**Comment by ameshkov** [comment]
Also link to easylist policy leads to 404, proper link: https://easylist.to/pages/policy.html

**Comment by vbagirov** [comment]
https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/374

**Comment by m67055** [comment]
I  do not  need  your  servic   delid my email
