### ISSUE TITLE
Adguard Ad Filters page changes

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#24]
1. Policy link should lead to KB
2. There should be a link to Adguard's github repo, so that people could report issues there

**Comment by ameshkov** [comment]
For every filter there should be a link to the platform specific rules (currently View all rules shows chromium rules)

**Comment by Crystal-RainSlide** [comment]
Where should I report issues for platform specific rules?

ublock Origin support  `google.*##.bad-stuff`, so its rules can use scheme like this but not `google.com,google.cat...`

**Comment by ameshkov** [comment]
Yep
