### ISSUE TITLE
Hotspot issue is not a problem since Android 7

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#270]
Update Android FAQ:
https://kb.adguard.com/en/android/faq#why-wi-fi-and-usb-tethering-do-not-work-with-adguard

**Comment by Dariamag** [comment]
Looks like it's already resolved?

**Comment by ameshkov** [comment]
Well, you could say so, the whole FAQ needs to be rewritten from scratch anyways.
