### ISSUE TITLE
"How to block ads in Youtube app" root-access app out of date

### ISSUE THREAD

**Issue by jeffreymcclain** [AdguardTeam/AdguardKnowledgeBase#288]
https://kb.adguard.com/en/android/solving-problems/youtube-ads

"If you have ROOT access, you can add AdGuard certificate to the system via the [Move Certs](https://f-droid.org/repository/browse/?fdfilter=move%20certs&fdid=com.nutomic.zertman) app." 

This app no longer exists on the F-Droid store? The previous sentence also references "April", which sounds like it would be the previous April, but in fact is all the way back from 2016.

Lastly, I think the title should be changed to explain the root system certificate process works for more than just Youtube ads, also Facebook Messenger and others. https://forum.adguard.com/index.php?threads/apps-where-adguard-for-android-cant-filter-and-or-remove-the-ads-from.25189/

**Comment by ameshkov** [comment]
@TheHasagi the article needs to be changed as now it's possible to move the certificate via AG settings.

> also Facebook Messenger and others

It won't help with the Facebook apps as they use SSL pinning and check the server cert on their own.

**Comment by TheHasagi** [comment]
Waiting for replication.
