### ISSUE TITLE
Add dark theme support for KB

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardKnowledgeBase#308]
@Rakleed commented on [Sat Mar 23 2019](https://github.com/AdguardTeam/AdguardForAndroid/issues/2663)

Если включена тёмная тема в AdGuard, и ты нажимаешь на знак "вопроса" (например, в настройках фильтрации DNS), то в webview открывается База знаний AdGuard с белым задним фоном. И получается очень не комфортно, когда в приложении тёмная тема, а сайт с белым задним фоном. Хотелось, чтобы при включённой тёмной теме в приложении сайт открывался с тёмным задним фоном или была простая возможность включить тёмный задний фон как, например, на [сайте с документацией по VBA для Microsft Office](https://docs.microsoft.com/ru-ru/office/vba/api/overview/).

**Comment by nataMai** [comment]
Moved to https://jira.adguard.com/browse/AG-10964

**Comment by rakleed** [comment]
@nataMai are you migrating all issues to your intern system and this repository will no longer be used for issues and contributions?

**Comment by nataMai** [comment]
@rakleed We continue to use this repository for issues and contributions.

**Comment by nataMai** [comment]
Moved to jira/AG-10964
