### ISSUE TITLE
Some wrong words.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardKnowledgeBase#327]
https://kb.adguard.com/en/android/solving-problems/background-work#Oneplus
Optimisation
-> Optimization
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/dgieOn0.jpg)
</details><br/>

**Comment by ameshkov** [comment]
Well, that's not a mistake actually:)

https://www.quora.com/Is-there-any-difference-between-optimization-and-optimisation
