### ISSUE TITLE
Slowly user profile scan

### ISSUE THREAD

**Issue by KrotyHomiaki** [AdguardTeam/AdguardKnowledgeBase#329]
![adguard_error](https://user-images.githubusercontent.com/50362124/57290975-2b5f9d00-70c7-11e9-9128-d188f99ebb72.png)
It scans the user profile very slowly after each reboot. I would like to be able to specify directories to be excluded from the scanning process.

**Comment by ameshkov** [comment]
@KrotyHomiaki а можете пожалуйста проверить есть ли это поведение на бета-версии AdGuard v7?

Вообще сканирует он `%appdata%` на предмет профилей Firefox чтобы проверить наличие сертификата. Он сканирует `%appdata%` когда ищет профили Firefox, но если мне память не изменяет, мы должны были этот процесс оптимизировать.

На всякий случай задачу я завел про это: https://github.com/AdguardTeam/CoreLibs/issues/890
