### ISSUE TITLE
Add the information about Yandex Safebrowsing

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardKnowledgeBase#33]
https://kb.adguard.com/ru/general/why-is-adguard-better

Do we still use it? If so, can we please add this to the kb or if we don't, remove the info from the official [site](https://adguard.com/ru/adblock-adguard-yandex-browser.html)

**Comment by vozersky** [comment]
We do occasionally use it, and not in real-time.
Not sure if it's worth mentioning.
