### ISSUE TITLE
DNS provider

### ISSUE THREAD

**Issue by bestpika** [AdguardTeam/AdguardKnowledgeBase#334]
- `02.general/17.dns-providers`
Now Google TLS over DNS server is `tls://dns.google`.
ref. <https://developers.google.com/speed/public-dns/docs/dns-over-tls>

If AdGuard Home use `tls://8.8.8.8` or `tls://8.8.4.4` will get the error.

- Quad9 DNS
It can also use `tls://dns.quad9.net`.
ref. <https://www.quad9.net/faq/#Does_Quad9_support_DNS_over_TLS>

**Comment by ameshkov** [comment]
Also, Google DOH is wrong: https://github.com/AdguardTeam/AdGuardHome/issues/759?email_source=notifications&email_token=ABNL5G5LP57KUUBJDWVEJEDPVVZARA5CNFSM4HNNCFU2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVSCSOY#issuecomment-493103419

**Comment by bestpika** [comment]
I found `https://dns.google.com/experimental` and `https://dns.google/experimental` are equal.

**Comment by m67055** [comment]
I do not  need   can  you  bock my  email

**Comment by bestpika** [comment]
@TheHasagi Google DoH change its address to `dns.google/dns-query`
ref. <https://developers.google.com/speed/public-dns/docs/doh/migration>

**Comment by TheHasagi** [comment]
@bestpika 

Yes, thank you. We already have an issue #369  :)
