### ISSUE TITLE
$csp script-src / style-src values given in example on website do not help to strengthen a given site’s policy.

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardKnowledgeBase#341]
**The following is a very-quickly written tutorial for the safe use of externally loaded scripts and stylesheets and is conditional on a specific feature of Content-Security-Policy functioning within AdGuard’s $csp modifier.**

*If* website (x) uses, e.g. cdnjs.cloudflare.com to load external stylesheets and/or scripts *then* do not use 'unsafe-eval', 'unsafe-inline' 'https:', 'blob:', data:', etc. - all of which are unsafe values for style-src & script-src, *and if* it is possible to use require-sri-for script style with AdGuard’s $csp modifier, *then use* `$csp require-sri-for script style` to ensure that only those scripts and styles used within any given website are those scripts and styles loaded via `cdn.x.example.com` or `cdn.y.example.com` have not been tampered with to inject malicious stylesheets or scripts. Real-word examples of how SRI hashes function on websites:

- Example Stylesheet served from `cdnjs.cloudflare.com` using subresource-integrity:

`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/3.0.1/github-markdown.css" integrity="sha384-JEAjzZ2SuTugMi1onOeXj5LyblbhGCa1U6TKYniTHW0Xli9SGkchIfxAB227r21a" crossorigin="anonymous">`

- Example Script served from `cdnjs.cloudflare.com` using subresource-integrity:

`<script src="https://cdnjs.cloudflare.com/ajax/libs/wysihtml5/0.3.0/wysihtml5.min.js" integrity="sha384-PnQt2OMXYkEzb0JokcAmMcT5g2xbk1w3l8isPt7kTZ2OHnVnC2xcxy8iUsiIet/C" crossorigin="anonymous"></script>`

** EDIT; **Note: Consider implementing strong security headers on AdGuard.com in order to lead by example. As I’m sure the dev team is aware, doing so via Cloudflare’s Workers simplifies the process over implementing the necessary various headers directly within your server.**

**Comment by ameshkov** [comment]
@mozdevcontrib please note that `$csp` modifier **adds** a new CSP policy, and not modifies the existing one.

For instance, let's consider that your website's policy is `script-src unsafe-inline sha384-xxxxx`
And you add the rule from the example: `script-src 'self' 'unsafe-eval' http: https:`

Every script on the webpage will be checked against **both** these policies.
Therefore, a `$csp` rule can strengthen the website's policy, but it cannot relax it.

**Comment by mozdevcontrib** [comment]
@ameshkov Understood. However, adding `script-src 'self' 'unsafe-eval' http: https:` does not strengthen a given script-src. It does, however, tell those sites with no CSP to use an essentially unsafe policy. Perhaps, in the knowledge base, the given example should be one that does strengthen a given site’s policy?

**Comment by ameshkov** [comment]
@mozdevcontrib 

> It does, however, tell those sites with no CSP to use an essentially unsafe policy. Perhaps, in the knowledge base, the given example should be one that does strengthen a given site’s policy?

Well, it does strengthen it a little bit -- it prohibits inline scripts :)

> Perhaps, in the knowledge base, the given example should be one that does strengthen a given site’s policy?

Hm, I never considered this way of using it.

Indeed, $csp modified can be used to achieve something like what `noscript` does automatically, but that would be rather tedious.

**Comment by ameshkov** [comment]
We will definitely add the explanation that $csp cannot possibly relax the existing website's content security policy.

I'll give it a thought about the possible use of $csp to strengthen CSP of the websites that don't use it. There are no filter lists doing it, but if there were, I would call it `CSP Everywhere` :)

**Comment by mozdevcontrib** [comment]
Sounds like a great name!

- intr0

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mozdevcontrib** [comment]
Certainly, which opens the idea of using the strict-dynamic policy with either randomly generated nonce-values or a hash-value as in your example. Simply using the require-sri-for script style value to one's policy greatly helps to strengthen any given site's security. And, of course, frame-ancestors is an extremely important value to set to 'none'.

- intr0

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mozdevcontrib** [comment]
> We will definitely add the explanation that $csp cannot possibly relax the existing website's content security policy.
> 
> I'll give it a thought about the possible use of $csp to strengthen CSP of the websites that don't use it. There are no filter lists doing it, but if there were, I would call it `CSP Everywhere` :)

I’ve been experimenting with Firefox’s extension for Linux. It works great to strengthen policies. It’s amazing how many sites aren’t using Content-Security-Policy as a security measure. Also, I just wanted to say that allowing unsafe-eval in scripts (eval) is just as insecure as using inline scripts. CSS is also an easy attack vector. Injecting malicious stylesheets can have the same effects as injecting malicious scripts.

**Comment by ameshkov** [comment]
> Also, I just wanted to say that allowing unsafe-eval in scripts (eval) is just as insecure as using inline scripts.

Well, I am not that optimistic about CSP in general, and these directives in particular. Disabling `unsafe-eval` is problematic by itself as it breaks a lot of useful javascript libraries. Don't forget that javascript by itself cannot be an attack vector, this is just a tool.

So let's consider what are these vectors. I'd mention these two:

1. Rogue browser extensions;
2. Rogue service providers (third-party javascript);

CSP cannot fully protect you from rogue browser extensions, so the only thing why you might need it is to protect yourself from the misbehavior of third-party javascript. And by "yourself" I mean website owners.

For instance, a website can be using a lot of different third-party tracking scripts, or maybe some third-party plugins (cookie notices, share buttons, web chats, whatever). If any of these goes rogue, you need CSP to protect yourself from what they can do.

The best protection would be to use `nonce-` or `sha-` directives, it will completely protect you from any unexpected changes. The problem is that it is **VERY HARD** to maintain such CSP even when you're a website owner, and I doubt it's humanly possible for an author of a filter list.

For a filter list, I guess it'd be possible to maintain a list of policies with allowed javascript sources

> And I hope you wouldn’t mind, if I did create a FireFox CSP filter, if I used the CSP Everywhere name. I’ve not thought of one better. :)

Of course:)

**Comment by mozdevcontrib** [comment]
Let’s avoid any script-src, and all directives that fall back on default-src. What are the other important directives? These: frame-ancestors, upgrade-all-insecure-requests, block-all-mixed-content, require-sri-for script style. The latter cannot be said to be difficult to implement or maintain. And it ensures that any third party scripts or stylesheets are those being requested. Beyond rogue providers and rogue extensions, both of which can be avoided by anyone with even a tiny bit of intelligence and awareness. I know there’s other points I’d wanted to make but I’m tired. Thanks for the continued discussion.

**Comment by ameshkov** [comment]
> What are the other important directives? These: frame-ancestors, upgrade-all-insecure-requests, block-all-mixed-content

Yeah, these are really easy to use and they make sense. 

> , require-sri-for script style.

`require-sri-for` requires websites' owners to change every `<script>` tag and add the `integrity` attribute, otherwise, it will simply block every script on the page.

> Beyond rogue providers and rogue extensions, both of which can be avoided by anyone with even a tiny bit of intelligence and awareness.

Well, I wouldn't say that about rogue third-party script sources. Here's an [example](https://nakedsecurity.sophos.com/2018/11/13/wordpress-gdpr-compliance-plugin-hacked/).

**Comment by mozdevcontrib** [comment]
> Well, I wouldn't say that about rogue third-party script sources.

##### `https://nakedsecurity.sophos.com/2018/11/13/wordpress-gdpr-compliance-plugin-hacked/`

I see that's a WordPress add-on. I, mistakenly, thought that when referring to add-ons, you meant browser add-ons. Yes, in the wild, plug-ins and add-ons for any WordPress-like, CMS, website builder, etc., there are many malicious ones out there. Then again, WordPress is problematic for anyone who does not familiarize one's self with its functionality, PHP, best-practices for security, etc.. Anyone who blindly uses WordPress, self-hosted or not, is asking for problems beyond those of a security issue. The majority of issues with one of my two current hosting providers are issues with WordPress.

_To repeat my main point for anyone who may read this: WordPress is NOT a solution for those not fully familiarized with the platform. And using a hosting provider as opposed to self-hosting does not automatically protect one's self from security issues._

**So, I fully agree on that point now that I understand to what you were referring**.

> Yeah, these are really easy to use and they make sense.

These are the directives I am currently using in my AdGuard Firefox extension:

`$csp=frame-ancestors 'none' upgrade-insecure-requests block-all-mixed-content require-sri-for script style`

And they work quite well.

**Comment by ameshkov** [comment]
Huh, even `require-sri-for script`? Isn't it breaking a lot of websites?
