### ISSUE TITLE
Add an article on How to create a HAR file in the browsers for the desktop

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardKnowledgeBase#354]
Добавьте статью о том, как создать HAR-файл в Google Chrome, Mozilla Firefox, Microsoft Edge и т. д. на десктопе. А то сейчас есть только статья для [Android](https://kb.adguard.com/android/solving-problems/har).

**Comment by Alex-302** [comment]
На основе этого можно сделать:
https://toolbox.googleapps.com/apps/har_analyzer/

**Comment by Rakleed** [comment]
@TheHasagi почему закрыли issue?

**Comment by TheHasagi** [comment]
В скором времени статья появится в [KB](kb.adguard.com).
