### ISSUE TITLE
Create article about collecting a full log on Adguard for Windows

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/AdguardKnowledgeBase#38]
This type of info available only for Android - https://kb.adguard.com/en/android/solving-problems/log

**Comment by Dariamag** [comment]
https://kb.adguard.com/en/windows/solving-problems/system-logs
https://kb.adguard.com/en/windows/solving-problems/adguard-logs

@adbuker Is this enough or do we need to update these articles?
