### ISSUE TITLE
Заглавные страницы разделов (файлы chapter.*.md)

### ISSUE THREAD

**Issue by Xottab-DUTY** [AdguardTeam/AdguardKnowledgeBase#384]
Когда впервые [открыл](https://github.com/AdguardTeam/AdguardKnowledgeBase/blob/master/11.home/chapter.ru.md) заглавную страницу раздела AdGuard Home, я подумал, что она ещё не загрузилась и ждал какое-то время. Потом понял, что ничего не загрузится, ибо это всё, что там есть.
Оказывается, оно так оформлено. И красиво оформлено! Но...

Предлагаю *очень аккуратно* добавить на этих страницах ссылки на дочерние страницы. (подразделы)

Именно очень аккуратно, потому что текущий дизайн выглядит красиво (!), но не интуитивно понятно, что нужно после выбора раздела, в том же блоке навигации, выбрать подраздел. И это не очень удобно. Например, я перешёл на вышеупомянутую заглавную страницу и сразу увёл курсор в центр экрана, подготовив его для клика на другие ссылки, которые могут быть на странице... А после этого мне пришлось *"долго"* возвращать его обратно к блоку навигации, чтобы выбрать подраздел.

Надо подумать как можно увеличить удобность, не испортив красоту.

P.S. В целом, выглядит как красивая презентация, ничего лишнего. Но, презентация удобна, если её вам кто-то показывает и переключает слайды. Но это же база знаний, а не презентация?) Здесь пользователь сам переключает страницы и в текущем виде есть некоторая неудобность.

**Comment by TheHasagi** [comment]
Это контент базы знаний находящейся по [ссылке](https://kb.adguard.com).

**Comment by Xottab-DUTY** [comment]
@TheHasagi, я и говорил про базу знаний, а не этот репозиторий!

**Comment by Xottab-DUTY** [comment]
Откройте обратно, пожалуйста
![trollsad](https://user-images.githubusercontent.com/2989212/61135655-894f9d00-a4db-11e9-83ec-1c017ea723d1.png)

**Comment by TheHasagi** [comment]
@Xottab-DUTY 

Не понимаю какую мысль Вы хотите донести. Страницы в [базе знаний](https://kb.adguard.com) соответствуют одному стилю оформления, если у Вас есть предложение оформите через pull request.

**Comment by vbagirov** [comment]
@Xottab-DUTY при существущем стиле оформления КБ мы не выводим на заглавную страницу раздела ссылки на отдельные главы. Чтобы сделать по-вашему, нам пришлось бы переделать оформление всех разделов, на это сейчас нет времени. Да мне лично и не кажется, что текущий вариант плох. Слева есть меню, в нём структура базы знаний видна, и даже, пожалуй, более явно.
