### ISSUE TITLE
Please rename Polish ads filter to Polish Anti Adblock Filters.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardKnowledgeBase#385]
https://kb.adguard.com/en/general/adguard-ad-filters

1. **Scroll down the page.**
Lack the titles of Filter unblocking search ads and self-promotion, Polish ads filter and Mobile ads filter in descriptions.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/Y8gEDEy.png)

![image](https://i.imgur.com/Cp8IIw9.png)
</details><br/>

2. Please rename `Polish ads filter` to `Polish Anti Adblock Filters`.
https://filters.adtidy.org/extension/chromium/filters/238.txt
! Title: Polish Anti Adblock Filters
! Description: Oficjalne polskie filtry przeciwko alertom o Adblocku

3. Maybe modify the link to Base filter?
now:
https://kb.adguard.com/en/general/adguard-ad-filters#english

new?
https://kb.adguard.com/en/general/adguard-ad-filters#base

If changing, please remember to modify the link in all AdGuard apps.

**Comment by Chinaski1** [comment]
@lancelot-moon 
About the first point 
Not quite clear, what's wrong there?
[Screenshot from KB](https://uploads.adguard.com/Chinaski5vtvf.png)

**Comment by lancelot-moon** [comment]
Weird.
At my side, I still don't see the titles of Filter unblocking search ads and self-promotion, Polish ads filter and Mobile ads filter in descriptions.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/Y8gEDEy.png)

![image](https://i.imgur.com/Cp8IIw9.png)
</details><br/>

**Comment by lancelot-moon** [comment]
Hi, I found the cause.
`280blocker for japanese mobile site` makes AG filters KB page broken.
https://280blocker.net/files/280blocker_adblock.txt

Please ignore the 1st point.
Sorry.

**Comment by Chinaski1** [comment]
Renamed!
