### ISSUE TITLE
Pre-processor directives remarks typo

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/AdguardKnowledgeBase#395]
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#remarks

> A conditional directive beginning with an #if directive must explicitly be terminated with an #endif directive

better `!#if` and `!#endif`

**Comment by Chinaski1** [comment]
[Fixed](https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/396)
