### ISSUE TITLE
Включение и выключение 2ФА

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardKnowledgeBase#403]
Стоит добавить статью о том, как включить и выключить двухфакторную аутентификацию для аккаунта. Или [статьи в блоге](https://adguard.com/ru/blog/adguard-2fa.html) достаточно?

**Comment by Chinaski1** [comment]
@Rakleed 
Добавил данную статью в Раздел общие вопросы. 
Со следующим обновлением Базы Знаний - появится.

**Comment by Rakleed** [comment]
@Chinaski1 а когда будет следующее обновление?
