### ISSUE TITLE
Stealth Mode: Information about Privacy levels (Android)

### ISSUE THREAD

**Issue by AlikhanAliev** [AdguardTeam/AdguardKnowledgeBase#431]
We should create elaborate texts about each privacy level for android app. Links to them will be in onboarding and settings flows.

**Comment by Dariamag** [comment]
https://jira.adguard.com/browse/AGM-674
in progress

**Comment by nataMai** [comment]
Moved to https://jira.adguard.com/browse/AG-10938

**Comment by nataMai** [comment]
Moved to jira/AG-10938
