### ISSUE TITLE
Please update Quad101 DNS and BlahDNS data in KB.

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#436]
@lancelot-moon commented on [Fri Oct 18 2019](https://github.com/AdguardTeam/dnsproxy/issues/69)

**Quad101 DNS:**
https://kb.adguard.com/en/general/dns-providers#quad101
https://101.101.101.101/index_en.html

From July 2018, it starts to support DoT.
From December 2018, it starts to support DoH.

DoT:
https://blog.twnic.net.tw/2018/07/02/1086/
Address: `tls://101.101.101.101`

DoH:
https://blog.twnic.net.tw/2018/12/28/1803/
Address: `https://dns.twnic.tw/dns-query`

**BlahDNS:**
https://kb.adguard.com/en/general/dns-providers#blahdns-germany
https://blahdns.com/

Japan server:
DoT:
`dot-jp.blahdns.com`

DoH:
`https://doh-jp.blahdns.com/dns-query`

Germany server:
DoT:
`dot-de.blahdns.com`

DoH:
`https://doh-de.blahdns.com/dns-query`

Switzerland server: IPv6 ONLY
DoT:
`dot-ch.blahdns.com`

DoH:
`https://doh-ch.blahdns.com/dns-query`

**Comment by ibksturm** [comment]
@ameshkov 

hi there, i will do it on sunday evening if that's ok
