### ISSUE TITLE
Create our own article about installing and configuring AdGuard Home in Docker

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardKnowledgeBase#439]
Like this one: https://gugucomputing.wordpress.com/2019/07/11/新dns去廣告神器-adguard-home-簡單版pi-hole/#more-867

**Comment by ameshkov** [comment]
Hmm, we could create a Wiki page with the list of useful articles about AdGuard Home for instance?

**Comment by vbagirov** [comment]
https://github.com/AdguardTeam/Adguardhome/wiki/Docker
