### ISSUE TITLE
[windows/installation] Fix uninstallation instruction for Windows 8/8.1

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardKnowledgeBase#443]
### Description

As of now, the uninstallation instruction for Windows 8/8.1 looks like this:

> For Microsoft Windows 8.1, 8 and 7: Open Start Menu. In the search box, type Control Panel. Click Uninstall a program in the Programs section, then select Adguard from the list of installed apps and press the Uninstall button located right above the list. Confirm the action by clicking Uninstall AdGuard in the window that opens.

### Issue

Windows 8/8.1 do not have a Start menu. They have a dedicated Start screen with an entirely different layout.

**Windows 8**
Windows 8 does not have neither Start menu nor Start button. 

![programs-pinned-to-taskbar](https://user-images.githubusercontent.com/33634917/67587644-03d7bc00-f75d-11e9-97c9-dbd55a236e97.png)

To access Control Panel, user has to right-click on the empty space in the lower left corner of the task bar and select Control Panel. 

**Windows 8.1**
Windows 8.1 has a Start button. User has to right-click on Start button and select "Control panel".

**Comment by Chinaski1** [comment]
@akmLaVx 
Can you provide the necessary screenshots for this task? I'll add them soon.

**Comment by akmLaVx** [comment]
Sure - will need to fire up a VM for this, so this might take a day or two.

**Comment by lolka4toli** [comment]
And... done.
