### ISSUE TITLE
Add a paragraph about safari_cb_affinity

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/AdguardKnowledgeBase#461]
that's a new [pre-processor directive](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#pre-processor-directives) and I suppose it should be mentioned about in KB

https://github.com/AdguardTeam/AdguardForiOS/issues/1104

**Comment by airobot60** [comment]
> that's a new [pre-processor directive](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#pre-processor-directives) and I suppose it should be mentioned about in KB
> 
> 
> 
> https://github.com/AdguardTeam/AdguardForiOS/issues/1104

**Comment by ameshkov** [comment]
@slavaleleka please also include the description of where the most popular filter lists belong (base, social, tracking protection, annoyances, lang specific)
