### ISSUE TITLE
Here's an example of a mistake.

### ISSUE THREAD

**Issue by adhu2018** [AdguardTeam/AdguardKnowledgeBase#464]
`https://cdn.adguard.com/public/Adguard/kb/en/rules_syntax/1_exact_address.svg`  
Depending on the context, the example in this link has an error and should be changed to `|http://example.org/`.

**Comment by ameshkov** [comment]
Thank you! We've fixed the image, but it will take some time for the cache to reload.

You can check the new image here:
https://cdn.adguard.com/public/Adguard/kb/en/rules_syntax/1_exact_address.svg?13333
