### ISSUE TITLE
Changes in $badfilter+$domain rules semantics

### ISSUE THREAD

**Issue by sxgunchenko** [AdguardTeam/AdguardKnowledgeBase#469]
After release of https://github.com/AdguardTeam/CoreLibs/issues/1241 it will be possible to disable a rule that fulfills all the following conditions:
* does have a domain= option; and
* does not have a negated domain in its domain= option; and
* does not have csp= option; and
* does not have a redirect= option

only for one domain by corresponding `$badfilter` rule with the `$domain` modifier set to the desired domain.
For example the rule `/some$domain=example.com|example.org` may be disabled for example.com by `/some$domain=example.com,badfilter`, but it'll still be matched for example.org.

Please note that it's not possible to disable several domains from the list in this way (i.e. /some$domain=example.com|example.org|example.ru can't be disabled for example.org and example.com by /some$domain=example.com|example.org).

**Comment by sxgunchenko** [comment]
After https://github.com/AdguardTeam/CoreLibs/issues/1331 the logic has been modified. Now a `$badfilter` rule can disable some rule for some domains in case it fulfils the following conditions:
* does have a `$domain` option; and
* does not have a negated domain in its `$domain` option.

In that case, the `$badfilter` rule disables corresponding rule for domains specified in both the `$badfilter` and basic rules. Please note, that wildcard-TLD logic (https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#wildcard-for-tld) works here as well. 

Examples: 
1) `/some$domain=example.com|example.org|example.io` is disabled for `example.com` by `/some$domain=example.com,badfilter`
2) `/some$domain=example.com|example.org|example.io` is disabled for `example.com` and `example.org` by `/some$domain=example.com|example.org,badfilter`
3) `/some$domain=example.com|example.org` and `/some$domain=example.io` are disabled completely by `/some$domain=example.com|example.org|example.io,badfilter`
4) `/some$domain=example.com|example.org|example.io` is disabled completely by `/some$domain=example.*,badfilter`
5) `/some$domain=example.*` is disabled for `example.com` and `example.org` by `/some$domain=example.com|example.org,badfilter`
6) `/some$domain=example.com|example.org|example.io` is NOT disabled for `example.com` by `/some$domain=example.com|~example.org,badfilter` because it has the negated domain

**Comment by vbagirov** [comment]
https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/654/
