### ISSUE TITLE
Add new Cloudflare DNS-resolvers to the article

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardKnowledgeBase#486]
https://kb.adguard.com/en/general/dns-providers#cloudflare-dns

add [new resolvers](https://blog.cloudflare.com/introducing-1-1-1-1-for-families/) with malware\adult content blocking:

Malware Blocking Only
Primary DNS: 1.1.1.2
Secondary DNS: 1.0.0.2

Malware and Adult Content
Primary DNS: 1.1.1.3
Secondary DNS: 1.0.0.3

For IPv6 use:

Malware Blocking Only
Primary DNS: 2606:4700:4700::1112
Secondary DNS: 2606:4700:4700::1002

Malware and Adult Content
Primary DNS: 2606:4700:4700::1113
Secondary DNS: 2606:4700:4700::1003

**Comment by lancelot-moon** [comment]
I missed the DoH stamp.
https://community.cloudflare.com/t/community-tip-best-practices-for-1-1-1-1-for-families/160496
Now new Cloudflare DNS-resolvers only support DoH, but will also support DoT in the future.
DoH:
Malware Blocking Only:
`security.cloudflare-dns.com`

Malware and Adult Content:
`family.cloudflare-dns.com`

**Comment by lancelot-moon** [comment]
Hi,
I update the DoH addresses.

**Comment by vbagirov** [comment]
https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/492
