### ISSUE TITLE
Scriptlets and redirect resources section

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/AdguardKnowledgeBase#490]
Add to KB at least small section about scriptlets and redirects which will lead to [doc on github](https://github.com/AdguardTeam/Scriptlets#adguard-scriptlets-and-redirect-resources) for more details

**Comment by vbagirov** [comment]
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#scriptlet-rules
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#redirect-modifier
