### ISSUE TITLE
Update the cosmetic rules section

### ISSUE THREAD

**Issue by sxgunchenko** [AdguardTeam/AdguardKnowledgeBase#505]
With the release of CoreLibs 1.6 it will be possible to modify the cosmetic rules behavior. 
The modifiers and their syntax are described here: https://gist.githubusercontent.com/sxgunchenko/efeb72ccadd2c49b36e5798802bc00e9/raw/d4b2e7e67454c1dea764e19ca754d47cb28f06bf/Cosmetic%2520rules%2520modifiers%2520syntax

Besides that, the new modifiers are also applicable for the HTML and JavaScript rules.
So, there is a sense to place the CSS (currently called *cosmetic*) and those 2 types of rules under the common paragraph `Cosmetic rules`.

**Comment by slavaleleka** [comment]
different AdGuard products support different set of rule types. so I suggest not to unite CSS, HTML and JavaScript rules under 'Cosmetic rules'
