### ISSUE TITLE
Улучшение статьи про DNS (ANDROID)

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardKnowledgeBase#544]
Здравствуйте,
Прошу внести изменения в статью о DNS (**ANDROID**).
Установка пользовательского DNS на данный момент возможна и без установки вашего приложения.
Начиная с 8 версии андроида нужно проделать следующие шаги:
Настройки -> Подключения -> Другие настройки -> Персональный DNS сервер -> Вводим dns.adguard.com -> подтверждаем -> Готово

Заранее спасибо!

**Comment by el-termikael** [comment]
Проверила, в статье нашей Базы знаний указана 9-ая версия Android, но [так и должно быть](https://developer.android.com/about/versions/pie/android-9.0-changes-28).

По поводу инструкции: да, возможна, но если вы используете AdGuard для Android, возможны конфликты private DNS и нашего DNS. Лучше настраивать DNS-сервер непосредственно в приложении (к тому же, там можно выбрать другой протокол, не только DNS-over-TLS).
