### ISSUE TITLE
Улучшение статьи про режим локального прокси (ANDROID)

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardKnowledgeBase#545]
Здравствуйте,
Прошу внести изменения в статью о режиме локального proxy **(ANDROID)**. Для фильтрации трафика через мобильные сети в режиме локального прокси больше не нужны Root права. Начиная с андроид версии 8 и выше для этого потребуется совершить ряд следующих действий: Настройки -> Подключения -> Мобильные сети -> Точки доступа -> Кликнуть по уже выбранному -> внести нужные настройки в пункт "proxy" и "port" -> подтверждаем -> готово

**Comment by el-termikael** [comment]
Здравствуйте!
У нас есть два режима локального прокси: автоматический и ручной. Автоматический режим требует root-доступа, а ручной нет, там нужна настройка, которая есть [в статье](https://kb.adguard.com/ru/android/faq#http) в разделе «Как работает фильтрация HTTPS» (и которую вы сами описали).
