### ISSUE TITLE
An article about mixed-approach to ad blocking

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#58]
Ideally, I'd like to have it as a blog post.

**Mixed approach:**
1. Enable simplified domain names filter
2. Disable Adguard for all apps except browsers and DNS (and maybe Anrdoid OS -- we should test it).
3. Enable "Filter DNS requests"
4. Enable HTTPS filtering.

So, in-app ads will be blocked by the DNS filtering, and in-browser ads will be nicely blocked by default filtering.

We should ask people to try it and give their feedback. If they like it, we might add a simple switch for enabling this filtering mode.

**Comment by Dariamag** [comment]
Still relevant? @ameshkov

**Comment by ameshkov** [comment]
Not really
