### ISSUE TITLE
Update HTTPS filtering article

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#60]
We should update status of the TLSv1.3 issue according to this comment: https://github.com/AdguardTeam/AdguardForWindows/issues/1737#issuecomment-302839792

**Comment by ameshkov** [comment]
We should also update the release dates.

**Comment by vbagirov** [comment]
Think it is done: https://kb.adguard.com/general/https-filtering/https-filtering-known-issues#tls-v1-3-support
