### ISSUE TITLE
A typo in the example

### ISSUE THREAD

**Issue by trmdi** [AdguardTeam/AdguardKnowledgeBase#600]
This: https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters?utm_source=browser_extension&utm_medium=options&utm_campaign=userfilter_description#example-blocking-by-domain-name-1

The rule:  ||example.org ^
It says:

    This rule does not block:
    http://example.org/redirect/http://ads.example.org/

I think the example is not right.

**Comment by ameshkov** [comment]
Yeah, it should've been:
`http://example.com/redirect/http://ads.example.org/`
