### ISSUE TITLE
Update the "outbound proxy" article

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#61]
Talking about this:
https://kb.adguard.com/ru/android/solving-problems/adguard-outbound-proxy

First, we should give some general advice there.
Then, we should have a section for every known provider.

How to use Adguard with Tor
How to use Adguard with PIA (Private Internet Access)
How to use Adguard with Torguard

**Comment by holmogorov** [comment]
Where can I find a basic information for each of these topics?

**Comment by ameshkov** [comment]
Let's delay this task a bit as outbound proxy functionality will be seriously updated in the next major AG update.

**Comment by vbagirov** [comment]
Updated.
