### ISSUE TITLE
An article about Big Sur issues

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#621]
https://kb.adguard.com/en/macos/solving-problems

We should add an article about solving Big Sur issues:

* Compatibility with local proxies -- explain how to configure an upstream proxy in AdGuard for Mac (`upstream.proxy`, `upstream.proxy.socks5udp` advanced settings). Provide examples -- the most popular cases -- how to setup Shadowsocks, Surge.
* Fixing an issue with accepting connections to your Mac -- if you use your Mac as a server, using network extension would break it. The solution would be to use `network.extension.route.exclude` advanced setting.
* How to enable the kernel extension in Big Sur -- solves lots of compatibility issues, but not recommended as it requires disabling security protections.
* Using "Automatic proxy" filtering mode when nothing else helps.

**Comment by vbagirov** [comment]
https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/646
https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/652
