### ISSUE TITLE
Add "Hints" description to the filter rules syntax article

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#63]
Hints description:
https://github.com/AdguardTeam/AdguardFilters/issues/3708#issuecomment-303155314
https://github.com/AdguardTeam/AdguardFilters/issues/5073

https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters

**Comment by ameshkov** [comment]
@holmogorov we need to add one more platform -- `ext_opera`: 
https://github.com/AdguardTeam/AdguardFilters/issues/5488

**Comment by vbagirov** [comment]
PR merged.
