### ISSUE TITLE
Broken links on the DNS page

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#647]
Broken links:

* https://kb.adguard.com/en/general/dns-providers#ibksturm
* https://kb.adguard.com/en/general/dns-providers#ffmuc.net
* https://kb.adguard.com/en/general/dns-providers#strongarm-dns
* https://kb.adguard.com/en/general/dns-providers#freenom-world

**Comment by vbagirov** [comment]
https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/658
