### ISSUE TITLE
Add a "cheatsheet" article about filter rules

### ISSUE THREAD

**Issue by sc0rp10** [AdguardTeam/AdguardKnowledgeBase#67]
Sometimes we need to add a simple rule for blocking a single URL, but KB have no examples for trivial cases.
I think we should start 'Basic rules' page with a list of trivial cases.

**Comment by ameshkov** [comment]
Basically, we need to provide a simple cheat sheet covering the trivial cases.

For instance:

1. Just blocking a request by URL
2. Blocking whole domain
3. Hiding an element

**Comment by ameshkov** [comment]
Regarding the examples, I reckon we should do it in the same manner as it's done here:
https://adblockplus.org/filter-cheatsheet

**Proposed plan of the cheatsheet**

* Browser developer tools [for Firefox](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools#How_to_open_the_devtools_in_your_browser) [for Chrome](https://developer.chrome.com/devtools)

Below are different rule types.

* Comments
* Basic rules
    * Example 1: Blocking by address parts
    * Example 2: Blocking by domain name
    * Example 3: Blocking exact address
    * Options in blocking rules
* Basic exception rules
    * Example 1: Exception for particular requests
    * Example 2: Exception for an entire site
* Cosmetic rules
    * Introduction into CSS selectors (https://adblockplus.org/filter-cheatsheet#elementselection)
    * Example 1: Element hiding rule for a particular domain
    * Example 2: Element hiding exception rule
    * Example 3: CSS rule


@seanl-adg @Alex-302 @AdamWr

Guys, what would you like to be added?

**Comment by ameshkov** [comment]
Regarding `Introduction into CSS selectors`, it'd be great to accompany selectors with simple screenshots. Something like this:

Selector | Description
------------ | -------------
##banner | Matches the element with the unique id `banner`: ![example domain 2017-06-14 11-34-20](https://user-images.githubusercontent.com/5947035/27123120-8b07e058-50f5-11e7-85a0-862d8f8b45e5.png)
.banner | Matches all elements with class `banner`:  ![example domain 2017-06-14 11-33-30](https://user-images.githubusercontent.com/5947035/27123139-9ca6ce6e-50f5-11e7-804b-1891953bf668.png)

**Comment by Alex-302** [comment]
***not finished***
-------
* Comments
The string, that begins with an exclamation mark.
Example:
`! some text`
* Basic rules
  * Special characters:
`||` - the beginning of an address - `http://`, `https://`, `ws://`, `wss://` at once;
`^` - separator character. It is any character, except a `0-9`, `_`, `-`, `.` ***??? ->*** and end of line
The most frequently used: `/`, `?`, `&`
Example of URL to which the separator is applicable:
`http://example.com/?param1=a&param1=b`
`*` - wildcard character. Used to represent an empty string, a string of any length or any character;
`|` - a pointer of the beginning or the end of the address
Example:
    * beginning of URL:
`|http://`, `|https://`, `ws://`, `wss://`
    * ending of URL:
`/advert.gif|`
  * Blocking by address parts


    * Examples:
    URLs:
    `http://example.com/banners/ads/advert.gif`
    `http://example.com/banners/img.gifs/`
    `http://example.com/banners/not_ads/image.png`
    `https://ads.example.com/img/1.jpg`
    `https://example.com/img/1.jpg`
    Rules:
    `^banners/*` - will block whole `http://example.com/banners/`
    `^banners/*.gif|` - will block requests to all GIF images in `http://example.com/banners/` and its subdirectoryes, but not `http://example.com/banners/img.gifs/`
    `|https://ads.` will block `ads` subdomain on the sites which are using HTTPS only. `http://example.com?url=https://ads.example.org` will not be blocked.
    `://ads.` will block `ads` subdomain on the sites which are using HTTP, HTTPS and web-sockets(WS and WSS). Subdomain for `ads` will not be blocked. For example: `https://css.ads.example.com`
  * Example 2: Blocking by domain name
  * Example 3: Blocking exact address
  * Options in blocking rules

**Comment by ameshkov** [comment]
@Alex-302 this will be a part of the existing KB article, so we shouldn't repeat the special characters part for instance.

The purpose of this cheatsheet is just to start from showing a few common examples.

**Comment by Alex-302** [comment]
But existing KB article is already contains examples. I thought I should to make a short separate cheatsheet.
So should this cheatsheet to contains only examples without explanation for the syntax?

**Comment by ameshkov** [comment]
> But existing KB article is already contains examples. I thought I should to make a short separate cheatsheet.

More or less, I just think it should be in the same article.

> So should this cheatsheet to contains only examples without explanation for the syntax?

We can link the existing article instead of repeating the same.

**Comment by Alex-302** [comment]
Something like that?
https://github.com/AdguardTeam/AdguardKnowledgeBase/issues/67#issuecomment-309278224

**Comment by ameshkov** [comment]
Yeah, but I'd prefer to have a better explanation.

Something like that:

### Example 1: Blocking by address parts
```
/banner/*/img^
```

**Rule parts**
* `/banner/` and `/img` -- **Verbatim text**. This text must be present in the address to be blocked.
* `*` -- **[Wildcard character](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#basic-rules-special-characters)**. This stands for any number of characters.
* `^` -- **[Separator](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#basic-rules-special-characters)**. The address must either end here or a separator character like ? or / has to follow.

**This rule blocks:**
- `http://example.org/banner/foo/img`
- `http://example.org/banner/foo/bar/img?param`
- `http://example.org/banner/img/foo`

**This rule doesn't block:**
- `http://example.org/banner/img`
- `http://example.org/banner/foo/imgraph`
- `http://example.org/banner/foo/img.gif`

**Comment by Alex-302** [comment]
## [Comments](#comments)
`! This is the comment.`
 - `!` — This symbol at the beginning of the rule indicates a comment;
 - `This is the comment.` — comment text.

## [Basic rules](#basic-rules)

>  * ### Example 1: Blocking by address parts

```
/banner/*/img^
```

#### Rule parts

* `/banner/` and `/img` — **Verbatim text**. This text must be present in the address to be blocked;
* `*` — **[Wildcard character](https://kb.adguard.com/general/how-to-create-your-own-ad-filters#basic-rules-special-characters)**. This stands for any number of characters;
* `^` — **[Separator](https://kb.adguard.com/general/how-to-create-your-own-ad-filters#basic-rules-special-characters)**. The address must either end here or a separator character like ? or / has to follow.

#### This rule blocks:
- `http://example.com/banner/ads/img`
- `http://example.com/banner/ads/bar/img?param`
- `http://example.com/banner/img/ad1`

#### This rule doesn't block:
- `http://example.com/banner/img`
- `http://example.com/banner/ads/imgraph`
- `http://example.com/banner/ads/img.gif`

>  * ### Example 2: Blocking by domain name
```
||ads.example.com^
```

**Rule parts**
* `ads.example.com` — **Verbatim text**. This text must be present in the address to be blocked;
* `||` — **[Matching the beginning of an address](https://kb.adguard.com/general/how-to-create-your-own-ad-filters#basic-rules-special-characters)**. `http://`, `https://`, `ws://`, `wss://` at once;
* `^` — **[Separator](https://kb.adguard.com/general/how-to-create-your-own-ad-filters#basic-rules-special-characters)**. The address must either end here or a separator character like ? or / has to follow.

**This rule blocks:**
- `http://ads.example.com/ad1.gif`
- `http://server1.ads.example.com/ad1.gif`
- `https://ads.example.com:8000/`

**This rule doesn't block:**
- `http://ads.example.com.ua/ad1.gif`
- `http://example.com/redirect/http://ads.example.com/`

>  * ### Example 3: Blocking exact address
```
|http://example.com/|
```

**Rule parts**
* `http://example.com/` — **Verbatim text**. This text must be present in the address to be blocked.
* `|` — **[A pointer to the beginning or the end of address](https://kb.adguard.com/general/how-to-create-your-own-ad-filters#basic-rules-special-characters)**.

**This rule blocks:**
- `http://example.com/`

**This rule doesn't block:**
- `http://example.com/banner/img`
- `http://example.com/banner/ads/img.gif`

>  * ### [Options in blocking rules](https://kb.adguard.com/general/how-to-create-your-own-ad-filters#basic-modifiers)
```
||ads.example.com^$script,image,domain=example.com|~foo.example.info
```
**Rule parts**
* `||` — **[Matching the beginning of an address](https://kb.adguard.com/general/how-to-create-your-own-ad-filters#basic-rules-special-characters)**. `http://`, `https://`, `ws://`, `wss://` at once;
* `ads.example.com` — **Verbatim text**. This text must be present in the address to be blocked;
 * `^` — **[Separator](https://kb.adguard.com/general/how-to-create-your-own-ad-filters#basic-rules-special-characters)**. The address must either end here or a separator character like ? or / has to follow;
* `$` — **[option separator](https://kb.adguard.com/general/how-to-create-your-own-ad-filters#attention)**. This character indicates that the following text defines filter option;
* `script`, `image` — **[Restriction by content type](https://kb.adguard.com/general/how-to-create-your-own-ad-filters#restriction-by-content-type)**. Type options define request types to be blocked.
* `domain` — **[Domain option](https://kb.adguard.com/general/how-to-create-your-own-ad-filters#basic-modifiers)**. Limits the rule application area to a list of domains (and their subdomains).

## [Basic exception rules](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#exception-modifiers)
>  * ### Example 1: Exception for particular requests

```
@@||ads.example.com/notbanner^$~script
```

#### Rule parts
* `@@` — **[Exception marker](https://kb.adguard.com/general/how-to-create-your-own-ad-filters#basic-rules-syntax-1)**. Rules starting like this are exceptions, they will override blocking rules;
* `||` — **[Matching the beginning of an address](https://kb.adguard.com/general/how-to-create-your-own-ad-filters#basic-rules-special-characters)**. `http://`, `https://`, `ws://`, `wss://` at once;
* `ads.example.com/notbanner` — **Verbatim text**. This text must be present in the address to be blocked;
* `^` — **[Separator](https://kb.adguard.com/general/how-to-create-your-own-ad-filters#basic-rules-special-characters)**. The address must either end here or a separator character like ? or / has to follow;
* `$` — **[option separator](https://kb.adguard.com/general/how-to-create-your-own-ad-filters#attention)**. This character indicates that the following text defines filter option;
* `~script` — **[Restriction by content type](https://kb.adguard.com/general/how-to-create-your-own-ad-filters#restriction-by-content-type)**. This type option prevents the exception from being applied to scripts.

>  * ### Example 2: Exception for an entire site

```
@@||example.com^$document
```

#### Rule parts
* `@@` — **[Exception marker](https://kb.adguard.com/general/how-to-create-your-own-ad-filters#basic-rules-syntax-1)**. Rules starting like this are exceptions, they will override blocking rules;
* `||` — **[Matching the beginning of an address](https://kb.adguard.com/general/how-to-create-your-own-ad-filters#basic-rules-special-characters)**. `http://`, `https://`, `ws://`, `wss://` at once;
* `ads.example.com/notbanner` — **Verbatim text**. This text must be present in the address to be blocked;
* `^` — **[Separator](https://kb.adguard.com/general/how-to-create-your-own-ad-filters#basic-rules-special-characters)**. The address must either end here or a separator character like ? or / has to follow;
* `$` — **[option separator](https://kb.adguard.com/general/how-to-create-your-own-ad-filters#attention)**. This character indicates that the following text defines filter option;
* `document` — **[Whole exception](https://kb.adguard.com/general/how-to-create-your-own-ad-filters#document)**. This option completely disables blocking for corresponding pages.




##### not finished

<details>

---

## [Cosmetic rules](https://kb.adguard.com/general/how-to-create-your-own-ad-filters#cosmetic-rules-1)

Introduction into CSS selectors (https://adblockplus.org/filter-cheatsheet#elementselection)
Example 1: Element hiding rule for a particular domain
Example 2: Element hiding exception rule
Example 3: CSS rule

* [Cosmetic rules](#cosmetic-rules)
    * Introduction into CSS selectors (https://adblockplus.org/filter-cheatsheet#elementselection)

    Selector | Description
    ------------ | -------------
    div[class="banners"] | Matches the element with the unique class `banners`: ![image](https://user-images.githubusercontent.com/8361299/27262479-6515da62-5460-11e7-8ca8-a097e369787b.png)
    #banners | Matches all elements with ID `banners`:  ![image](https://user-images.githubusercontent.com/8361299/27262517-b9b070dc-5460-11e7-95ba-ca799745d007.png)
    div[class^="advert"] | Matches div elements that start with class `advert`: ![image](https://user-images.githubusercontent.com/8361299/27262695-e048012a-5464-11e7-8a2b-b2996426803e.png)
    div[class$="banners_ads"] | Matches div elements that end with class `banners_ads`: ![image](https://user-images.githubusercontent.com/8361299/27262734-b0f3ced0-5465-11e7-9f54-e7accd58e60f.png)
    a[href="http://example.com/"] | Matches links to http://example.com/: ![image](https://user-images.githubusercontent.com/8361299/27262625-5d369fc2-5463-11e7-8f9d-1a85e26ab91a.png)
    a[href^="http://example.com/"] | Matches links to any pages hosted on http://example.com/: ![image](https://user-images.githubusercontent.com/8361299/27262644-b8a874fc-5463-11e7-974a-82fe90d54338.png)



    * Example 1: Element hiding rule for a particular domain
`example.com##div[class="adverts"]`
    * Example 2: Element hiding exception rule
`example.com#@#div[class="adverts"]`
    * Example 3: CSS rule
       * Remove backgroung image:
`example.com#$#body { background: none!important; }`
       * Change element height for avoid primitive ad blocking detection:
`example.com#$#div[id^="ad_"] { height: 1px!important; }`



</details>
