### ISSUE TITLE
Separator description

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#68]
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#basic-rules-special-characters

We should add one more sentence to `^` description:

> The end of the address is also accepted as separator.

**Comment by Alex-302** [comment]
@ameshkov 
> The end of the address is also accepted as separator.

Is it only Adguard specific? This does not match to ABP syntax
https://adblockplus.org/filter-cheatsheet#blocking1

**Comment by ameshkov** [comment]
> Is it only Adguard specific? This does not match to ABP syntax

It matches ABP syntax actually:
https://adblockplus.org/en/filters#separators

**Comment by vbagirov** [comment]
Done
