### ISSUE TITLE
Add "Strip URLs from tracking parameters" detailed description 

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#69]
This is a new feature of the "Stealth Mode" module.

List of parameters being removed:
```
            "utm_source",
            "utm_medium",
            "utm_term",
            "utm_content",
            "utm_campaign",
            "utm_referrer",
            "yclid",
            "gclid",
            "_openstat",
            "fb_action_ids",
            "fb_comment_id",
            "fb_action_types",
            "fb_ref",
            "fb_source",
            "action_object_map",
            "action_type_map",
            "action_ref_map"
```

Helpful links:

* https://en.wikipedia.org/wiki/UTM_parameters
* https://developers.facebook.com/docs/games/services/measurement#referraltracking
* http://fbdevwiki.com/wiki/Ref

**Comment by holmogorov** [comment]
May you provide the URL of page/section at KB where there I should to make changes please?

**Comment by ameshkov** [comment]
@holmogorov to figure out what it is you should install the latest AdGuard beta version and check the "Stealth Mode" settings.

When "Strip URLs from tracking parameters" option is enabled, AdGuard automatically removes parameters listed above from the pages URLs, therefore it prevents some of the tracking methods. 

This functionality is similar to what this add-on does: https://addons.mozilla.org/en-US/firefox/addon/pure-url/
