### ISSUE TITLE
Instruction for users who cannot install the AdGuard app (MAC)

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardKnowledgeBase#696]
Need to add the specified instruction

For details, please contact me at PM

**Comment by Chinaski1** [comment]
Только в инструкции от експресса not permitted, а тут not found, соответственно надо будет расписать оба варианта действий

**Comment by Chinaski1** [comment]
Also, be advisable if you add short instructions for users who use the proxy applications in pair with the AdGuard app for macOS.

In short, the auto-proxy should be deactivated in the system configurations and configured in the [Advanced settings](https://uploads.adguard.com/Chinaskicwj9y.png) of AdGuard.  



For additional info, you can contact @ngorskikh

**Comment by lolka4toli** [comment]
Seems like outdated.

**Comment by lolka4toli** [comment]
Looking outdated.
