### ISSUE TITLE
Filters policy, add a clear definition of tracker and "third-party"

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#700]
I like how it's worded by WebKit devs:
https://webkit.org/tracking-prevention-policy/

@AdguardTeam/filters-maintainers guys, please share your thoughts.

Let's discuss it here first.

**Comment by BlazDT** [comment]
Agree about definitions there.

**Comment by vbagirov** [comment]
https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/714
