### ISSUE TITLE
awarding the best AdGuard contributors

### ISSUE THREAD

**Issue by el-termikael** [AdguardTeam/AdguardKnowledgeBase#718]
Hello, @bigdargon @Aikatsui @krystian3w @PentagramTr @superlex

My name is Helen, I'm a content manager at AdGuard, and currently, we’re preparing a blog post about the most active community contributors of the year. All of you undoubtedly deserve a spot there. Congratulations and big thanks for your help!

Please contact me at `e.ter-mikaelyan@adguard.com` to discuss the best way to send you our special gift bag and other details.

**Comment by ameshkov** [comment]
@bigdargon @Aikatsui @krystian3w @PentagramTr @superlex

Sorry for using this way, we just don't have any other way to reach out.

Closing this issue since it's meant to be just a notification/announcement and not a real issue.

**Comment by krystian3w** [comment]
https://github.com/MasterKia/PersianBlocker/issues/1
