### ISSUE TITLE
Update $removeparam rules description

### ISSUE THREAD

**Issue by sxgunchenko** [AdguardTeam/AdguardKnowledgeBase#719]
In the CoreLibs 1.8 the `$removeparam` rules syntax and behaviour will be changed.
The complete description is here: https://github.com/uBlockOrigin/uBlock-issues/issues/1356#issuecomment-736291101.
CoreLibs' issue for reference: https://github.com/AdguardTeam/CoreLibs/issues/1384

**Comment by vbagirov** [comment]
https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/774
