### ISSUE TITLE
Add a "noop" modifier description

### ISSUE THREAD

**Issue by sxgunchenko** [AdguardTeam/AdguardKnowledgeBase#722]
A noop modifier does nothing and can be used to increase some rules readability. 
It consists of the sequence of underscore characters (`_`) of any length and can appear in a rule as many times as it's needed.
Examples:
`||example.com$_,removeparam=/^ss\\$/,_,image`
`||example.com$replace=/bad/good/,___,~third-party`

Original CoreLibs issue for reference: https://github.com/AdguardTeam/CoreLibs/issues/1387

**Comment by vbagirov** [comment]
https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/773
