### ISSUE TITLE
Error 500 in beta testing program form

### ISSUE THREAD

**Issue by karaluh** [AdguardTeam/AdguardKnowledgeBase#723]
I know this is not entirely the right place to file this bug but there is no other AdGuard project with the "website" tag.

I tried to apply for the beta at https://surveys.adguard.com/beta_testing_program/form.html but when I try to submit the form I get error 500.

**Comment by ameshkov** [comment]
Should be resolved already, thank you!

**Comment by karaluh** [comment]
Unfortunately, it's not.

**Comment by ameshkov** [comment]
Hmm, sorry for that, we'll check it asap

**Comment by karaluh** [comment]
Any progress on this?

**Comment by ameshkov** [comment]
Very sorry for the delay, website deploy was postponed. I hope tomorrow we'll finally roll out the fix.

**Comment by karaluh** [comment]
I still have this error, any updated ETA of the roll out?

**Comment by ameshkov** [comment]
@karaluh seems to be okay now

**Comment by karaluh** [comment]
Yes, the application went through, thank you.
