### ISSUE TITLE
Add support for the Brazilian Portuguese language

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdguardKnowledgeBase#726]
https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/725

I started translating the pages and a page is ready

**Comment by nataMai** [comment]
https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/725

Our current platform does not support Knowledge Base translations to Brazilian Portuguese. We have been considering moving to another platform in the not-so-distant future. 
More information is available here:
https://kb.adguard.com/en/miscellaneous/updating-kb#translating
