### ISSUE TITLE
Improve HAR files article

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#73]
https://kb.adguard.com/en/android/solving-problems/har

We should add the following information:

* What are HAR files?
* How to analyze HAR files (known tools)

**Comment by holmogorov** [comment]
Where can I find the source information for these topics?

**Comment by ameshkov** [comment]
HAR analyzer tool:
http://gitgrimbo.github.io/harviewer/master/

HAR spec:
http://www.softwareishard.com/blog/har-12-spec/

Don't make description too detailed, just provide these links and add a short introduction.

**Comment by ameshkov** [comment]
Fiddler also allows importing HAR files:
http://www.telerik.com/fiddler
