### ISSUE TITLE
Add information about regular expressions support on :contains and :matches-css

### ISSUE THREAD

**Issue by theseanl** [AdguardTeam/AdguardKnowledgeBase#74]
https://github.com/AdguardTeam/ExtendedCss/issues/29

**Comment by ameshkov** [comment]
Afterwards we should also add links to https://github.com/AdguardTeam/ExtendedCss/blob/master/README.md

**Comment by ameshkov** [comment]
@seanl-adg please write a simple technical description here, what should be added to the article: https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#pseudo-class-contains
