### ISSUE TITLE
Add KB info for Xiaomi MIUI 12 background work (battery optimization)

### ISSUE THREAD

**Issue by oroboros** [AdguardTeam/AdguardKnowledgeBase#753]
The KB for the Xiaomi section includes instructions for MIUI 10/11.

https://kb.adguard.com/en/android/solving-problems/background-work?utm_source=android&utm_medium=app_notification_background_work&utm_campaign=background_work#Xiaomi

Below are the updated instructions for MIUI 12, that you can verify and update. 
Screenshots can be accessed from [here](https://gofile.io/d/AFt67k) or PM me directly.

### MIUI 12

To ensure that MIUI 12 doesn't close AdGuard while it's running in the background, please follow these steps.

**1. Pin app**

Go to _Recent tasks_ and long-press on AdGuard (NB: AdGuard must be open).
Tap on the _Lock_ icon. This will stop MIUI from closing AdGuard automatically in the background. You will then see a lock icon next to the app name.

[IMG1][IMG2]

**2. Set permissions**

From the same _Recent tasks_ menu, tap on the App info _bolt_ icon (last icon) (NB: Alternatively, go to _Settings > Apps > Manage apps > AdGuard_). Under Permissions:
- Set _Autostart_ to “On” 
- Set _Battery saver_ to “No restrictions”.

[IMG3][IMG4]

**Comment by Chinaski1** [comment]
Hello there!

We'll be sure to add instructions for MIUI 12 shortly.

**Comment by oroboros** [comment]
@Chinaski1 @lolka4toli Since it's simply copy-pasting the text to the KB webpage, is there a way I can do it since it seems you all are busy?

**Comment by el-termikael** [comment]
@oroboros done https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/770

**Comment by oroboros** [comment]
@el-termikael Should it be live by now? Because I do not see these updates: https://kb.adguard.com/en/android/solving-problems/background-work?utm_source=android&utm_medium=app_notification_background_work&utm_campaign=background_work#Xiaomi

**Comment by el-termikael** [comment]
Not yet, the changes will appear on the website a bit later.17.03.2021, 10:50, "oroboros" ***@***.***>:
@el-termikael Should it be live by now? Because I do not see these updates: https://kb.adguard.com/en/android/solving-problems/background-work?utm_source=android&utm_medium=app_notification_background_work&utm_campaign=background_work#Xiaomi

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Sincerely,HelenAdGuard team

**Comment by oroboros** [comment]
Hi @el-termikael !

I'm trying to refer someone to the guide. I thought this would be live now after 3 weeks. Am I missing something?

**Comment by el-termikael** [comment]
@oroboros Hi!

Here are the updated instructions: https://kb.adguard.com/en/android/solving-problems/background-work#miui-12

**Comment by oroboros** [comment]
@el-termikael 

Thanks for this. I guess I didn't see it under Xiaomi, since it's at the very bottom (!). 
It's odd to have a 3-yr old OS version show up first as the most prominent KB instruction, and not the latest MIUI version right under the Xiaomi label.

The main problem here is that, unlike the text I suggested which was self-standing, this starts by saying saying "MIUI 12: All steps are almost the same" - as if the user of MIUI 12 (the latest) needs to be aware of the steps of the previous versions. 
Quite confusing! 
I'm not sure why not using the simpler instructions and screenshots provided in my OP: https://github.com/AdguardTeam/AdguardKnowledgeBase/issues/753#issue-808425346

But it is up to you. I'm happy to have contributed in some way.
