### ISSUE TITLE
Update DNS filtering rules syntax

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#765]
1. AdGuard Home now supports more modifiers.
2. AdGuard for Windows and AG for Mac are also getting DNS filtering support so the article should reflect this:
https://kb.adguard.com/en/general/dns-filtering-syntax

Also, the introduction does not highlight the benefits of DNS filtering:
```
Compared to traditional content blocking, DNS filtering is more "crude" and allows less customization, but it starts working earlier, even before apps actually make a connection attempt.
```

**Comment by vbagirov** [comment]
https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/766
