### ISSUE TITLE
Add str to get http log on Android

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardKnowledgeBase#77]
https://kb.adguard.com/en/android/solving-problems/log

"не помешала бы такая же статья (а точнее раздел с anchor) про http лог. Он чаще нужен, а пояснения юзерам писать долго"

**Comment by ameshkov** [comment]
@vozersky wouldn't it be better if we add "Export" option to the program's filtering log?

**Comment by vozersky** [comment]
@ameshkov  that would be great, and I wish we could export state.txt data as well
