### ISSUE TITLE
使用adguard有感

### ISSUE THREAD

**Issue by fancyLSH** [AdguardTeam/AdguardKnowledgeBase#780]
最近用为一点事故重装了系统之后，网页弹窗真的是尤其多，让人心烦，上网搜索发现有一款叫做adguard的拦截软件，下载后发现效果还不错，真的值得推荐

**Comment by kingforme** [comment]
在此区域发issues仅供提交错误

**Comment by DashaBu** [comment]
我们很感谢您使用 AdGuard！
这里您可以留下与知识库（https://kb.adguard.com/）有关的反馈意见。
您可以在我们的QQ群（https://jq.qq.com/?_wv=1027&k=NBICRLoE）、新浪微博（https://weibo.com/u/7457831289）或 Telegram 群（https://t.me/AdGuard_chinese）里与其他用户讨论 AdGuard 应用程序。

**Comment by fancyLSH** [comment]
> ```
> 最近用为一点事故重装了系统之后，网页弹窗真的是尤其多，让人心烦，上网搜索发现有一款叫做adguard的拦截软件，下载后发现效果还不错，真的值得推荐。
> 同时，写文章还可以免费得adguard的授权码，可谓是一举两得呀，真的是蛮开心的。
> ```

**Comment by fancyLSH** [comment]
我已经发表了文章，麻烦给我一个授权码，谢谢。

发送自 Windows 10 版邮件应用

发件人: Dasha_Bu
发送时间: 2021年3月25日 16:36
收件人: AdguardTeam/AdguardKnowledgeBase
抄送: fancyLSH; Author
主题: Re: [AdguardTeam/AdguardKnowledgeBase] 使用adguard有感 (#780)

Closed #780.
