### ISSUE TITLE
Removing DNSCepat from known DNS providers

### ISSUE THREAD

**Issue by tina-hello** [AdguardTeam/AdguardKnowledgeBase#783]
Their homepage return 404, all of the listed endpoint except DNS IPv4 (can't check the IPv6 because I don't have them) are down. I would just create a pull request except I don't know if there's a procedure for removing a provider.

**Comment by Aikatsui** [comment]
DNSCepat project maintainer @malhuda2 added it 3 months ago https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/729
I think he may able to fix it soon or provide an update here.
