### ISSUE TITLE
[vpn] manual configuration instructions for vpn profile

### ISSUE THREAD

**Issue by kaznovac** [AdguardTeam/AdguardKnowledgeBase#798]
having the app for vpn is cool, but not essential for the basic connection.

the infrastructure is already in place for the rest of the clients (android, ios)
it would be great if you can provide the configuration instructions for the manual vpn profile creation.

e.g. i would like to configure and test the vpn on macos
on the ios (phone) i can see it's an IKEv2 protocol, server and account fields are clipped
(not sure if i can export/retrive the profile from ios)

**Comment by ameshkov** [comment]
Hmm, that's a good question.

You can retrieve the connection info in the app (there's a special authentication token that we use), but this token needs to be refreshed from time to time.

We'll open an internal ticket for this - we'll need to discuss this internally.
