### ISSUE TITLE
Article about DNS filtering in Android

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#86]
We will add a link to this article from Android UI:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1134#issue-217065786

We can re-use information from this post:
https://blog.adguard.com/en/great-battery-saving-mode-of-adguard-for-android/

Brief plan:
1. What is DNS?
2. How does DNS Filtering work? (blocks ad&tracking servers locally using simplified domain names filter and user filter).
3. What is DNSCrypt and why it is important? (I'd mention this: https://blog.adguard.com/en/dns-track-you/)

**Comment by vbagirov** [comment]
@ameshkov can we make it a part of an existing page about Adguard for Android features and add an anchor? Instead of creating a dedicated page, it would look weird with our current KB structure.

**Comment by ameshkov** [comment]
The same functionality might be provided by other products, so it makes sense to have a separate article.

**Comment by vbagirov** [comment]
@ameshkov So you mean creating it outside of Android section of KB? Like, 'General questions'? 

Or maybe we can create a new page inside the DNS section and call it 'DNS filtering in other Adguard products', with separate anchors for different products (Android, iOS etc).

**Comment by ameshkov** [comment]
I think it suits general section just okay.

**Comment by vbagirov** [comment]
https://kb.adguard.com/en/general/dns-filtering-android
https://kb.adguard.com/ru/general/dns-filtering-android

**Comment by ameshkov** [comment]
@vbagirov 

1. Let's rename it into a general article about DNS filtering, why Android only?
2. The 'How it works' section does not explain what happens at all. There is no definition of the DNS-level ad blocking. I suppose we should have a diagram with the explanation there.
3. Without an explanation, it's not clear what's the point in the SDN filter, etc.
4. DNSCrypt section should also include a diagram showing that DNS traffic is usually plain and easy to intercept/analyze. Also, it lacks a link to the dnscrypt.org.

**Comment by vbagirov** [comment]
@ameshkov 

 1. We have a whole chapter about Adguard DNS. It would be extremely inconsistent to have a separate article called 'DNS filtering' outside of it. Don't you think?
 2. Fair. Will update.
 3. Same as no. 2
 4. Do we have such diagram at the ready, or should I search for one? The link is easy to add, obviously, will do.

**Comment by ameshkov** [comment]
1. DNS filtering != DNS
4. We don't.

**Comment by vbagirov** [comment]
Committed to master. Soon will be on release, closing the issue.
