### ISSUE TITLE
Article about known proxy and VPN providers compatible with AdGuard

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#87]
The article is required for this task:
https://github.com/AdguardTeam/AdguardForAndroid/issues/968

Known proxy providers:
1. Orbot (Tor)
2. PIA
3. TorGuard

Instead of adding a new article, we should update the existing one:
https://kb.adguard.com/en/android/solving-problems/adguard-outbound-proxy

**Comment by ameshkov** [comment]
We should also explain what are the limitations:

1. AG re-routes traffic only for the apps with "Ad blocking" flag enabled.
2. AG does not route UDP through proxy.

**Comment by vbagirov** [comment]
Updated.
