### ISSUE TITLE
Add `$path` modifier description

### ISSUE THREAD

**Issue by sxgunchenko** [AdguardTeam/AdguardKnowledgeBase#878]
See https://github.com/AdguardTeam/CoreLibs/issues/124#issuecomment-846907007 for details

The modifier will be available after the release of CoreLibs version 1.9

**Comment by nataMai** [comment]
Moved to https://jira.adguard.com/browse/AG-10939

**Comment by nataMai** [comment]
Moved to jira/AG-10939

**Comment by nataMai** [comment]
Description updated
