### ISSUE TITLE
Update the `$removeparam` modifier description

### ISSUE THREAD

**Issue by sxgunchenko** [AdguardTeam/AdguardKnowledgeBase#924]
We need to add a note that a `$removeparam` rule which does not have any content-type modifiers, matches only the requests which have `document` request type.

https://github.com/AdguardTeam/CoreLibs/issues/1492 for reference

**Comment by nataMai** [comment]
Moved to https://jira.adguard.com/browse/AG-10940

**Comment by nataMai** [comment]
Moved to jira/AG-10940
