### ISSUE TITLE
Update the `$third-party` modifier description

### ISSUE THREAD

**Issue by sxgunchenko** [AdguardTeam/AdguardKnowledgeBase#955]
Since some browsers have started to send the [`Sec-Fetch-Site` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-Site) in HTTP requests, the CoreLibs have become able to detect third-party requests in more cases.

So, as the method of detecting third-party requests is different in the CoreLibs and the browser extension, it would be nice to describe add it in the [`$third-party` modifier section](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#third-party-modifier):
```
A request is considered as a third-party one if it meets one of the following conditions:
1) **actually it's already described there** - it has a referrer and the referrer is not a subdomain of the target domain (e.g., a request to `subdomain.example.org` from the domain `example.org` is not a third-party one)
2) **new one** - it has the `Sec-Fetch-Site` header set to `cross-site`
```

Link for reference: https://github.com/AdguardTeam/CoreLibs/issues/1523

**Comment by nataMai** [comment]
Moved to https://jira.adguard.com/browse/AG-10942

**Comment by nataMai** [comment]
Moved to jira/AG-10942
