### ISSUE TITLE
We need a document explaining low-level settings for each platform

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#956]
We have some really low-level flags in the apps which are supposed to be used only in rare edge cases.
Nevertheless, it'd be better to have a document that explains what these settings are.

On Windows it is called "Advanced Settings"
On macOS it is also called "Advanced Settings"
On Android it is called "Low-level settings"
On iOS it is called "Low-level settings"

Each setting should have a description -- what it actually does?

**Comment by nataMai** [comment]
Moved to https://jira.adguard.com/browse/AG-10943

**Comment by nataMai** [comment]
Moved to jira/AG-10943
