### ISSUE TITLE
Add information about iCloud Private Relay not working alongside AdGuard for Mac

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#957]
The problem with iCloud Private Relay is that you simply cannot do any filtering (including local filtering) when it is active.

Because of that, you cannot use it alongside AdGuard. Btw, the same applies to any VPN apps, it's either Private Relay or a VPN.

**Comment by nataMai** [comment]
Moved to https://jira.adguard.com/browse/AG-10941

**Comment by ameshkov** [comment]
@nataMai additional info on this: if the user REALLY REALLY wants to use AdGuard alongside Private Relay, they can switch AG filtering mode to proxy:

Preferences -> Network -> Select Mode -> choose Automatic Proxy.

**Comment by nataMai** [comment]
@ameshkov This documentation issue should be fixed in #977

**Comment by nataMai** [comment]
Moved to jira/AG-10941
