### ISSUE TITLE
Add an explanation about "Protect Mail Activity" feature

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardKnowledgeBase#959]
We might want to add it to the same place as "iCloud Private Relay" explanation.

![image](https://user-images.githubusercontent.com/5947035/139810312-217a047e-d100-42b8-94b5-2fa76e680e14.png)

Apple's Mail app now uses a proxy to hide user's IP address when downloading images from emails.

However, it won't work if there's an active VPN connection. It considers AdGuard a VPN as well so it just won't preload images automatically.

There is an explanation of that in Apple's documentation, we should link it.

**Comment by ameshkov** [comment]
@nataMai here's a very detailed explanation of both issues with iCloud Private Relay and Protect Mail Activity:
https://github.com/AdguardTeam/AdguardForMac/issues/979#issuecomment-957259568

**Comment by nataMai** [comment]
Progress status: 
Included in Jira: https://jira.adguard.com/browse/AG-11080

**Comment by nataMai** [comment]
@ameshkov Is this a proper link to the official Apple documentation regarding this issue? 
https://support.apple.com/en-us/HT212797

**Comment by ameshkov** [comment]
@nataMai yes, that's a right link.

Mail app considers AdGuard a VPN (even though it is not) and automatically disables itself. Unfortunately, there's no workaround for this.

We have pretty much the same issue on iOS since AdGuard operates as a "local VPN" there (so we might need to have two articles about that).

**Comment by nataMai** [comment]
Moved to jira/AG-11080
