### ISSUE TITLE
Add filtering quality level description

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardKnowledgeBase#96]
https://github.com/AdguardTeam/AdguardForAndroid/issues/1332#issuecomment-317214503

**Comment by vbagirov** [comment]
I think we should add this to FAQ, and this means we should update phrases in OneSky too. @aalpatkina please take care of it, talk to Android devs if needed.

**Comment by vbagirov** [comment]
We have FAQ in KB as well, so one doesn't hurt the other anyway.

**Comment by aalpatkina** [comment]
https://kb.adguard.com/en/android/faq#methods
