### ISSUE TITLE
Change app locking method description for MIUI 12.0.8+

### ISSUE THREAD

**Issue by Pipeliner** [AdguardTeam/AdguardKnowledgeBase#968]
As per https://forum.xda-developers.com/t/is-there-any-way-to-lock-apps-in-memory-on-miui-12-0-9.4267443/#post-84951191 (tested personally and seems to work)
Security app » Settings cog » Boost speed » Lock apps

**Comment by ameshkov** [comment]
@nataMai @vbagirov can we please update KB with this info asap? There're quite a lot of complaints about MIUI.

Also, we should notify the support service about a working solution.

**Comment by nataMai** [comment]
Started as the internal task https://jira.adguard.com/browse/AG-11202

**Comment by vbagirov** [comment]
This is already done on the test server, changes will soon appear on the production server too.

**Comment by nataMai** [comment]
Moved to jira/AG-11202
