### ISSUE TITLE
Add a compatibility chart for filters to filter rules article 

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardKnowledgeBase#97]
Suggested:
<details>

![image](http://imagizer.imageshack.com/img924/1728/MxzbmT.png)
</details>

[filters.xls.txt](https://github.com/AdguardTeam/AdguardKnowledgeBase/files/1172628/filters.xls.txt)
remove `.txt` from the file extension

On Google Docs:
https://docs.google.com/spreadsheets/d/1duRPrgoTrHZz4R170yg0Dw97miI0XGv0ru_1znC0UNE/edit?usp=sharing

**Comment by vbagirov** [comment]
Also we need to include these: 
https://github.com/AdguardTeam/AdguardKnowledgeBase/issues/139

**Comment by Alex-302** [comment]
Any news? For the third year there is no progress.

**Comment by ameshkov** [comment]
Well, you can pull request this as well :)
