### ISSUE TITLE
About `$queryprune`

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardKnowledgeBase#993]
https://github.com/uBlockOrigin/uAssets/commit/d67b7648733a20dd475cbeb19ba5cc4c344e3b20#commitcomment-61272559
> gorhill: We need to use removeparam instead of queryprune, I just fixed the documentation to warn about this.
---
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#removeparam
> To remove query parameters from the URL of network requests -- see also AdGuard's removeparam's documentation. For historical reasons, queryprune is an alias of removeparam (avoid using queryprune, it is deprecated and support will be removed eventually).
---
You may want to update this document:
https://github.com/AdguardTeam/AdguardKnowledgeBase/blob/master/01.general/02.how-to-create-your-own-ad-filters/docs.en.md#removeparam-modifier

**Comment by nataMai** [comment]
Created a task in jira/AG-11582
